### ISSUE TITLE
boolean nopreview opt type is not supported

### ISSUE THREAD

**Issue by smartrip** [vesteraas/campi#1]
Hi,

In the options.js file you define "nopreview" parameter as boolean (line 12), but the parser doesn't recognise it (line 62). In result it's never applied. I recommend to unify "nopreview" parameter with "hflip" and "vflip" and make them all state or boolean. 

I also think you should add a piece of code to recognise true/false state for these options to make the setup easier (I didn't read all of your your instructions and got stuck with flipping options applied even when I set them to false).

**Comment by vesteraas** [comment]
Hi!

Thank you for bringing this to my attention.
